# Generated by Django 2.1 on 2020-12-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiciyo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_s', models.CharField(max_length=100)),
                ('price_s', models.IntegerField()),
                ('image_s', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
