# Generated by Django 2.1 on 2020-12-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiciyo', '0002_slider_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='call_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.ImageField(max_length=10, upload_to='')),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
